# Generated by Django 5.2 on 2025-04-21 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_remove_media_album_remove_album_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='album',
        ),
        migrations.RemoveField(
            model_name='video',
            name='album',
        ),
        migrations.AddField(
            model_name='album',
            name='owner',
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='photos',
            field=models.ManyToManyField(
                related_name='albums', to='album.photo'),
        ),
        migrations.AddField(
            model_name='album',
            name='videos',
            field=models.ManyToManyField(
                related_name='albums', to='album.video'),
        ),
    ]
